# -*- coding: utf-8 -*-
"""CodeAlpha_Sentiment_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7eq1Fe0lsh0R6YbnNTc1TwJP0h_3dLC
"""

import pandas as pd

path = "/content/drive/MyDrive/CodeAlpha_SentimentAnalysis/new2_books_dataset_6_columns.csv"
df = pd.read_csv("/content/drive/MyDrive/CodeAlpha_SentimentAnalysis/new2_books_dataset_6_columns.csv", encoding="latin-1")
df.head()

!pip install nltk textblob vaderSentiment pandas matplotlib seaborn

import pandas as pd
import numpy as np
import nltk
import matplotlib.pyplot as plt
import seaborn as sns

from nltk.sentiment import SentimentIntensityAnalyzer
from textblob import TextBlob

TEXT_COLUMN = "Title"

df = df.dropna(subset=[TEXT_COLUMN])
df = df.reset_index(drop=True)

nltk.download("vader_lexicon")
sia = SentimentIntensityAnalyzer()

df["sentiment_scores"] = df[TEXT_COLUMN].apply(
    lambda x: sia.polarity_scores(str(x))
)

df["compound"] = df["sentiment_scores"].apply(lambda x: x["compound"])

def classify_sentiment(score):
    if score > 0.05:
        return "positive"
    elif score < -0.05:
        return "negative"
    else:
        return "neutral"

df["sentiment"] = df["compound"].apply(classify_sentiment)

df[[TEXT_COLUMN, "sentiment"]].head()

df["polarity"] = df[TEXT_COLUMN].apply(
    lambda x: TextBlob(str(x)).sentiment.polarity
)

df["subjectivity"] = df[TEXT_COLUMN].apply(
    lambda x: TextBlob(str(x)).sentiment.subjectivity
)

plt.figure(figsize=(6,4))
sns.countplot(x="sentiment", data=df)
plt.title("Sentiment Distribution of Book Titles")
plt.show()

df["sentiment"].value_counts()

plt.figure(figsize=(6,4))
sns.countplot(x="sentiment", data=df)
plt.title("Sentiment Count Distribution")
plt.show()

