# -*- coding: utf-8 -*-
"""CodeAlpha_Exploratory Data Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rAGegOgp5F46k83GnDtU63v_cRAGVjb9
"""

import pandas as pd

path = "/content/new2_books_dataset_6_columns.csv"
df = pd.read_csv("/content/new2_books_dataset_6_columns.csv", encoding="latin-1")
df.head()

df.info()
df.describe()

rating_map = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

df["Rating Numeric"] = df["Rating"].map(rating_map)

import pandas as pd
import matplotlib.pyplot as plt

plt.figure()
plt.hist(df["Price (£)"], bins=30)
plt.title("Distribution of Book Prices")
plt.xlabel("Price (£)")
plt.ylabel("Frequency")
plt.show()

avg_price_by_rating = df.groupby("Rating Numeric")["Price (£)"].mean()

plt.figure()
avg_price_by_rating.plot(kind="bar")
plt.title("Average Book Price by Rating")
plt.xlabel("Rating")
plt.ylabel("Average Price (£)")
plt.show()

plt.figure()
df["Category"].value_counts().head(10).plot(kind="bar")
plt.title("Top 10 Book Categories")
plt.xlabel("Category")
plt.ylabel("Number of Books")
plt.show()

plt.figure()
plt.hist(df["Stock Count"], bins=30)
plt.title("Distribution of Stock Counts")
plt.xlabel("Stock Count")
plt.ylabel("Frequency")
plt.show()

# Books marked in stock but having zero quantity
df[(df["Stock Count"] == 0) & (df["Availability"].str.contains("In stock"))]

#summary
print("Total books:", len(df))
print("Average price:", df["Price (£)"].mean())
print("Most common category:", df["Category"].mode()[0])
print("Average stock count:", df["Stock Count"].mean())